#!/usr/bin/env sh

# default config
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffa3685f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  15             \
    bottom_padding               15             \
    left_padding                 15             \
    right_padding                15             \
    window_gap                   05             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# spaces
yabai -m space 1 --label chat
yabai -m space 2 --label work
yabai -m space 3 --label main
yabai -m space 4 --label other

# rules
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref|Trash)" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="System Information" title="About This Mac" manage=off

yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^GIMP" manage=off
yabai -m rule --add app="^Inkscape" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="VirtualBox" manage=off
yabai -m rule --add app="^VLC$" manage=off

yabai -m rule --add app="^Arc" space=work
yabai -m rule --add app="^LibreWolf" space=main
yabai -m rule --add app="^Slack" space=chat
yabai -m rule --add app="^Thunderbird" space=chat

yabai -m rule --add app="^Android Studio$" manage=off space=other
yabai -m rule --add app="IntelliJ IDEA" manage=off space=work
yabai -m rule --add app="^Simulator" manage=off space=other
yabai -m rule --add app="^Tot$" manage=off
yabai -m rule --add app="^Xcode$" manage=off space=other
# float
yabai -m rule --add app="^LibreWolf" title="^Opening" manage=off
yabai -m rule --add app="^Thunderbird$" title="Sending Message" manage=off sticky=on
yabai -m rule --add app="^Xcode$" label="Archives" manage=off