#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        cursor
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

# layout settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

# spaces
yabai -m space 1 --label chat
yabai -m space 2 --label work
yabai -m space 3 --label main
yabai -m space 4 --label other

# rules
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref|Trash)" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="System Information" title="About This Mac" manage=off

yabai -m rule --add app="^balenaEtcher$" manage=off
# yabai -m rule --add app="^Cisco AnyConnect" manage=off
yabai -m rule --add app="^GIMP" manage=off
yabai -m rule --add app="^Inkscape" manage=off
yabai -m rule --add app="LocalSend" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="VirtualBox" manage=off
yabai -m rule --add app="^VLC$" manage=off

yabai -m rule --add app="^Firefox" title="^Opening" manage=off

yabai -m rule --add app="^Android Studio$" manage=off space=other
yabai -m rule --add app="^IntelliJ" manage=off space=work
#yabai -m rule --add label="IntelliJ IDEA" app="IntelliJ IDEA" manage=off space=work
yabai -m rule --add app="^Simulator" manage=off space=other
yabai -m rule --add app="^Tot$" manage=off
yabai -m rule --add app="^Xcode$" manage=off space=other
yabai -m rule --add app="^Xcode$" label="Archives" manage=off space=other
