# Brewfile
# brew bundle dump

brew "ack"
brew "coreutils"
# brew "curl"
brew "ffmpeg"
brew "findutils"
brew "git"
brew "gnu-sed"
brew "imagemagick"
brew "moreutils"
brew "ngrep"
# brew "p7zip"
# brew "python"
# brew "ruby"
# brew "telnet"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"

# personal
brew "bottom" # btm
brew "git-crypt"
brew "jq"
brew "neovim"

# MAMP Things (see mamp.sh)
# brew "dnsmasq", restart_service: true
# brew "mysql", restart_service: true, link: false

# Swift
# brew "swiftlint" # needs Xcode

# JS
# brew "n"
brew "fnm"

# GPG
brew "gnupg"
brew "pinentry-mac"

# Window Manager
tap "koekeishiya/formulae"
brew "skhd"
brew "yabai"

# fun
brew "cmatrix"
brew "exiftool"
brew "fortune"
brew "id3v2"
brew "lynx"
brew "nmap"
brew "toilet"
brew "yt-dlp"

# Casks
# cask "android-file-transfer"
# cask "android-studio"
# cask "arduino"
# cask "balenaetcher"
# cask "bettertouchtool"
# cask "boop"
# cask "calibre"
# cask "cyberduck"
# cask "discord"
# cask "dropbox"
cask "ghostty"
# cask "gimp"
cask "helium-browser"
# cask "inkscape"
# cask "itsycal"
# cask "keka"
# cask "keybase"
# cask "lagrange"
# cask "librewolf"
cask "localsend"
# cask "obsidian"
# cask "orbstack"
cask "sequel-ace"
cask "slack"
#cask "soduto"
# cask "syncthing-app"
# cask "tailscale-app"
# cask "thunderbird"
# cask "utm"
# cask "virtualbox"
# cask "vlc"
# cask "vscodium"
cask "yaak"
cask "zed"
cask "zen"

# Fonts
# cask "font-fira-mono-for-powerline"
cask "font-commit-mono"
cask "font-hack"
