#!/usr/bin/env sh

# Open Alacritty
cmd - return : open -na /Applications/Alacritty.app

# toggle window zoom
alt - f : yabai -m window --toggle zoom-fullscreen

# toggle window split type
alt - e : yabai -m window --toggle split

# focus window
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# move managed window
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# resize window
shift + alt - w : yabai -m window south --resize top:0:-20 2> /dev/null || yabai -m window --resize top:0:-20
shift + alt - a : yabai -m window west --resize right:-20:0 2> /dev/null || yabai -m window --resize right:-20:0
shift + alt - s : yabai -m window north --resize bottom:0:20 2> /dev/null || yabai -m window --resize bottom:0:20
shift + alt - d : yabai -m window east --resize left:20:0 2> /dev/null || yabai -m window --resize left:20:0

shift + alt - q : yabai -m window west --resize right:-100:0 2> /dev/null || yabai -m window --resize right:-100:0
shift + alt - e : yabai -m window east --resize left:100:0 2> /dev/null || yabai -m window --resize left:100:0

# balance size of windows
shift + alt - 0 : yabai -m space --balance

# focus monitor
ctrl + alt - 1 : yabai -m display --focus 1
ctrl + alt - 2 : yabai -m display --focus 2
ctrl + alt - z : yabai -m display --focus prev || yabai -m display --focus next

# focus next/prev spaces (NEEDS SIP)
#cmd + alt - z : yabai -m space --focus next || yabai -m space --focus first
#cmd + alt - c : yabai -m space --focus prev || yabai -m space --focus last

# float / unfloat window and center on screen
shift + alt - space : yabai -m window --toggle float; yabai -m window --grid 1:1:0:0:1:1

