local minipick = require('mini.pick')
minipick.setup()
vim.keymap.set('n', '<leader>pf', minipick.builtin.files) -- ':Pick files<CR>')
vim.keymap.set('n', '<leader>ps', minipick.builtin.grep_live) -- ':Pick grep live<CR>')
vim.keymap.set('n', '<leader>pb', minipick.builtin.buffers) -- ':Pick buffers<CR>')
-- vim.keymap.set('n', '<C-p>', function() minipick.builtin.files({ tool = 'git' }) end)
