#!/usr/bin/env bash

alias xi="sudo xbps-install -S"
alias xu="sudo xbps-install -Su"
alias xr="sudo xbps-remove -R"

# -O cleans cache
# -o remove installed packege orphans
alias xro="sudo xbps-remove -Oo"

# -R repository mode
# -s search
alias xs="sudo xbps-query -Rs"

