#!/usr/bin/env bash

# Set workspace
export WORKSPACE=$HOME/workspace

# Make vim the default editor.
export EDITOR=vim

# Prefer US English and use UTF-8.
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Go
export GOPATH=$HOME/.go

# Export path to include workspace scripts and Go
export PATH="/usr/local/sbin:$GOPATH/bin:$HOME/.local/bin:$PATH"

# Move things to .config
export ZDOTDIR="$HOME/.config/zsh"
# Set cache
export ZCACHE="$HOME/.cache/zsh"

[ ! -d $ZCACHE ] && mkdir -p $ZCACHE
