#!/usr/bin/env zsh
# Moving contents of .zprofile to .zshenv
# The order in which zsh startup files are run is:
# .zshenv → .zprofile → .zshrc → .zlogin → .zlogout

# zshenv needs to be symlinked to $HOME/.zshenv so that zsh knows where its configs are
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_BIN_HOME=${XDG_BIN_HOME:-$HOME/.local/bin}

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZCACHE="$XDG_CACHE_HOME/zsh"

# Create {.config,.cache}/zsh directories if they dont exist
[ ! -d $ZDOTDIR ] && mkdir -p $ZDOTDIR
[ ! -d $ZCACHE ] && mkdir -p $ZCACHE
